"""Database schema management.

Schema is owned by Alembic (``migrations/``), not by ``create_all``.

``create_all`` can only ever *add* tables. It cannot alter a column, add one to
an existing table, or backfill — so the first change to an existing table had
no path to production at all, and any drift between the models and a live
database was invisible. Every schema change now travels as a reviewable
migration.

Adopting an existing database is handled here too: a deployment created by the
old ``create_all`` path already has the tables but no ``alembic_version``.
Running an upgrade on it would try to CREATE tables that exist, so it is
*stamped* at the baseline instead. That is safe by construction — the baseline
revision was autogenerated from the same models ``create_all`` was building.
"""
from __future__ import annotations

import logging
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from sqlalchemy import Engine, inspect

from atlas.models import Base

log = logging.getLogger(__name__)

# The first revision, generated from the models as they stood when Alembic was
# adopted. Databases predating Alembic are stamped here rather than migrated.
BASELINE_REVISION = "21be828239fa"

# A table that only ever existed under the pre-Alembic schema — its presence
# without alembic_version is what identifies a database needing adoption.
_SENTINEL_TABLE = "workflow_runs"


def _alembic_config(engine: Engine) -> Config | None:
    """Locate alembic.ini by walking up from this file. ``None`` if absent."""
    for parent in Path(__file__).resolve().parents:
        ini = parent / "alembic.ini"
        if ini.is_file() and (parent / "migrations").is_dir():
            cfg = Config(str(ini))
            cfg.set_main_option("script_location", str(parent / "migrations"))
            cfg.attributes["connection"] = engine
            return cfg
    return None


def ensure_schema(engine: Engine) -> None:
    """Bring the database up to the latest revision."""
    cfg = _alembic_config(engine)
    if cfg is None:
        # Should not happen in a normal deployment. Falling back keeps the
        # appliance bootable rather than failing closed on a packaging
        # mistake, but it is loud: schema drift becomes possible again.
        log.error(
            "alembic.ini/migrations not found — falling back to create_all. "
            "Schema changes to existing tables will NOT be applied."
        )
        with engine.begin() as conn:
            Base.metadata.create_all(conn)
        return

    inspector = inspect(engine)
    tables = set(inspector.get_table_names())

    if _SENTINEL_TABLE in tables and "alembic_version" not in tables:
        log.info("Adopting pre-Alembic database — stamping baseline %s", BASELINE_REVISION)
        with engine.begin() as conn:
            cfg.attributes["connection"] = conn
            command.stamp(cfg, BASELINE_REVISION)

    with engine.begin() as conn:
        cfg.attributes["connection"] = conn
        context = MigrationContext.configure(conn)
        before = context.get_current_revision()
        command.upgrade(cfg, "head")

    if before is None:
        log.info("Database schema created at head")
    else:
        log.info("Database schema at head (was %s)", before)
