"""baseline schema

Revision ID: 21be828239fa
Revises: 
Create Date: 2026-08-28 09:21:06.618434
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '21be828239fa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_doc_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=120), nullable=False),
    sa.Column('doc_id', sa.String(length=256), nullable=False),
    sa.Column('active_doc_version', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'doc_id', name='uq_active_doc_versions_scope')
    )
    op.create_index(op.f('ix_active_doc_versions_doc_id'), 'active_doc_versions', ['doc_id'], unique=False)
    op.create_index(op.f('ix_active_doc_versions_project_id'), 'active_doc_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_active_doc_versions_tenant_id'), 'active_doc_versions', ['tenant_id'], unique=False)
    op.create_table('config_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_versions_config_hash'), 'config_versions', ['config_hash'], unique=False)
    op.create_table('corpora',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=120), nullable=False),
    sa.Column('corpus_id', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'corpus_id', name='uq_corpora_scope')
    )
    op.create_index(op.f('ix_corpora_corpus_id'), 'corpora', ['corpus_id'], unique=False)
    op.create_index(op.f('ix_corpora_is_active'), 'corpora', ['is_active'], unique=False)
    op.create_index(op.f('ix_corpora_project_id'), 'corpora', ['project_id'], unique=False)
    op.create_index(op.f('ix_corpora_tenant_id'), 'corpora', ['tenant_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', name='uq_projects_scope')
    )
    op.create_index(op.f('ix_projects_is_active'), 'projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_is_active'), 'tenants', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    op.create_table('vlm_page_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_vlm_page_cache_source_sha256'), 'vlm_page_cache', ['source_sha256'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=120), nullable=False),
    sa.Column('doc_id', sa.String(length=256), nullable=False),
    sa.Column('doc_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_node', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_doc_id'), 'workflow_runs', ['doc_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_project_id'), 'workflow_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_tenant_id'), 'workflow_runs', ['tenant_id'], unique=False)
    op.create_table('cleanup_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=120), nullable=False),
    sa.Column('corpus_id', sa.String(length=120), nullable=False),
    sa.Column('doc_id', sa.String(length=256), nullable=False),
    sa.Column('chunk_id', sa.String(length=256), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_span_start', sa.Integer(), nullable=True),
    sa.Column('source_span_end', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleanup_feedback_category'), 'cleanup_feedback', ['category'], unique=False)
    op.create_index(op.f('ix_cleanup_feedback_corpus_id'), 'cleanup_feedback', ['corpus_id'], unique=False)
    op.create_index(op.f('ix_cleanup_feedback_doc_id'), 'cleanup_feedback', ['doc_id'], unique=False)
    op.create_index(op.f('ix_cleanup_feedback_project_id'), 'cleanup_feedback', ['project_id'], unique=False)
    op.create_index(op.f('ix_cleanup_feedback_run_id'), 'cleanup_feedback', ['run_id'], unique=False)
    op.create_index(op.f('ix_cleanup_feedback_tenant_id'), 'cleanup_feedback', ['tenant_id'], unique=False)
    op.create_table('hitl_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=120), nullable=False),
    sa.Column('doc_id', sa.String(length=256), nullable=False),
    sa.Column('doc_version', sa.String(length=64), nullable=False),
    sa.Column('chunk_id', sa.String(length=256), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('judge_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=256), nullable=False),
    sa.Column('before_md', sa.Text(), nullable=False),
    sa.Column('after_md', sa.Text(), nullable=False),
    sa.Column('reason_for_edit', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hitl_tasks_doc_id'), 'hitl_tasks', ['doc_id'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_is_sensitive'), 'hitl_tasks', ['is_sensitive'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_priority_score'), 'hitl_tasks', ['priority_score'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_project_id'), 'hitl_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_run_id'), 'hitl_tasks', ['run_id'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_status'), 'hitl_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_hitl_tasks_tenant_id'), 'hitl_tasks', ['tenant_id'], unique=False)
    op.create_table('node_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('input_ref', sa.Text(), nullable=False),
    sa.Column('output_ref', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_runs_node_name'), 'node_runs', ['node_name'], unique=False)
    op.create_index(op.f('ix_node_runs_run_id'), 'node_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_node_runs_status'), 'node_runs', ['status'], unique=False)
    op.create_table('vlm_sessions',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('headless', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('stitched_markdown', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_vlm_sessions_run_id'), 'vlm_sessions', ['run_id'], unique=False)
    op.create_index(op.f('ix_vlm_sessions_source_sha256'), 'vlm_sessions', ['source_sha256'], unique=False)
    op.create_index(op.f('ix_vlm_sessions_status'), 'vlm_sessions', ['status'], unique=False)
    op.create_table('artifact_refs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('node_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['node_run_id'], ['node_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_refs_kind'), 'artifact_refs', ['kind'], unique=False)
    op.create_index(op.f('ix_artifact_refs_node_run_id'), 'artifact_refs', ['node_run_id'], unique=False)
    op.create_index(op.f('ix_artifact_refs_run_id'), 'artifact_refs', ['run_id'], unique=False)
    op.create_table('vlm_page_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['vlm_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'page_num', name='uq_vlm_page_session_page')
    )
    op.create_index(op.f('ix_vlm_page_results_cache_key'), 'vlm_page_results', ['cache_key'], unique=False)
    op.create_index(op.f('ix_vlm_page_results_session_id'), 'vlm_page_results', ['session_id'], unique=False)
    op.create_index(op.f('ix_vlm_page_results_status'), 'vlm_page_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vlm_page_results_status'), table_name='vlm_page_results')
    op.drop_index(op.f('ix_vlm_page_results_session_id'), table_name='vlm_page_results')
    op.drop_index(op.f('ix_vlm_page_results_cache_key'), table_name='vlm_page_results')
    op.drop_table('vlm_page_results')
    op.drop_index(op.f('ix_artifact_refs_run_id'), table_name='artifact_refs')
    op.drop_index(op.f('ix_artifact_refs_node_run_id'), table_name='artifact_refs')
    op.drop_index(op.f('ix_artifact_refs_kind'), table_name='artifact_refs')
    op.drop_table('artifact_refs')
    op.drop_index(op.f('ix_vlm_sessions_status'), table_name='vlm_sessions')
    op.drop_index(op.f('ix_vlm_sessions_source_sha256'), table_name='vlm_sessions')
    op.drop_index(op.f('ix_vlm_sessions_run_id'), table_name='vlm_sessions')
    op.drop_table('vlm_sessions')
    op.drop_index(op.f('ix_node_runs_status'), table_name='node_runs')
    op.drop_index(op.f('ix_node_runs_run_id'), table_name='node_runs')
    op.drop_index(op.f('ix_node_runs_node_name'), table_name='node_runs')
    op.drop_table('node_runs')
    op.drop_index(op.f('ix_hitl_tasks_tenant_id'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_status'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_run_id'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_project_id'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_priority_score'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_is_sensitive'), table_name='hitl_tasks')
    op.drop_index(op.f('ix_hitl_tasks_doc_id'), table_name='hitl_tasks')
    op.drop_table('hitl_tasks')
    op.drop_index(op.f('ix_cleanup_feedback_tenant_id'), table_name='cleanup_feedback')
    op.drop_index(op.f('ix_cleanup_feedback_run_id'), table_name='cleanup_feedback')
    op.drop_index(op.f('ix_cleanup_feedback_project_id'), table_name='cleanup_feedback')
    op.drop_index(op.f('ix_cleanup_feedback_doc_id'), table_name='cleanup_feedback')
    op.drop_index(op.f('ix_cleanup_feedback_corpus_id'), table_name='cleanup_feedback')
    op.drop_index(op.f('ix_cleanup_feedback_category'), table_name='cleanup_feedback')
    op.drop_table('cleanup_feedback')
    op.drop_index(op.f('ix_workflow_runs_tenant_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_project_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_doc_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_vlm_page_cache_source_sha256'), table_name='vlm_page_cache')
    op.drop_table('vlm_page_cache')
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_active'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_active'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_corpora_tenant_id'), table_name='corpora')
    op.drop_index(op.f('ix_corpora_project_id'), table_name='corpora')
    op.drop_index(op.f('ix_corpora_is_active'), table_name='corpora')
    op.drop_index(op.f('ix_corpora_corpus_id'), table_name='corpora')
    op.drop_table('corpora')
    op.drop_index(op.f('ix_config_versions_config_hash'), table_name='config_versions')
    op.drop_table('config_versions')
    op.drop_index(op.f('ix_active_doc_versions_tenant_id'), table_name='active_doc_versions')
    op.drop_index(op.f('ix_active_doc_versions_project_id'), table_name='active_doc_versions')
    op.drop_index(op.f('ix_active_doc_versions_doc_id'), table_name='active_doc_versions')
    op.drop_table('active_doc_versions')
    # ### end Alembic commands ###
